name: flutterdemo
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5
  dio: ^5.0.1
  logger: ^1.2.2
  pull_to_refresh_flutter3: ^2.0.1
  pull_to_refresh_notification: ^3.0.0
  flutter_datetime_picker: ^1.5.1
  flutter_picker: ^2.1.0
  flutter_easy_permission: ^1.1.2
  image_picker: ^0.8.6+4
  flutter_screenutil: ^5.6.1
  connectivity: ^3.0.6
  file_picker: ^5.2.5
  event_bus: ^2.0.0
  flutter_smart_dialog: ^4.8.2+5
  flutter_swiper_null_safety: ^1.0.2
  keframe: ^3.0.0
  extended_image: ^7.0.2
  extended_text_field: ^11.0.0
  extended_tabs: ^4.0.2
  extended_text: ^10.0.0
  shared_preferences: ^2.0.18
  intl: ^0.18.0
  tuple: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
